'use client';

import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';

export default function Page() {
  const router = useRouter();
  const [downloading, setDownloading] = useState(false);
  const [shared, setShared] = useState(false);

  function handleDownload() {
    setDownloading(true);
    // Simulate a download action
    setTimeout(() => {
      setDownloading(false);
      // Create a simple text file as ticket download
      const ticketData = `
=== RailConnect Digital Ticket ===
Booking Reference: VBE882910
Status: CONFIRMED

JOURNEY DETAILS
---------------
Train: RailConnect Express (22436)
From: New Delhi (NDLS) — Platform 16  at 06:00 AM
To:   Varanasi Jn (BSB)  — Platform 1  at 02:00 PM
Duration: 8h 00m

PASSENGER
---------
Name:  Rajesh Kumar
Coach: C2 | Seat: 24 (Window) | Class: AC Chair Car

TICKET INFO
-----------
PNR: 244-9812233
Date: Oct 24, 2024
Fare: ₹ 1,750.00

Generated by RailConnect — Kinetic Heritage.
`;
      const blob = new Blob([ticketData], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'RailConnect_Ticket_VBE882910.txt';
      a.click();
      URL.revokeObjectURL(url);
    }, 1000);
  }

  function handleShare() {
    if (navigator.share) {
      navigator.share({
        title: 'RailConnect Ticket — VBE882910',
        text: 'New Delhi → Varanasi | Oct 24, 2024 | Train 22436 | Seat 24 (Window)',
        url: window.location.href,
      }).then(() => setShared(true));
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(
        'RailConnect Booking VBE882910 | New Delhi → Varanasi | Oct 24, 2024 | Train 22436 | Seat 24 (Window) | PNR: 244-9812233'
      ).then(() => {
        setShared(true);
        setTimeout(() => setShared(false), 3000);
        alert('📋 Ticket details copied to clipboard!');
      });
    }
  }

  function handleManageBooking() {
    const action = window.confirm(
      'Manage Booking Options:\n\nClick OK to Cancel this booking\nClick Cancel to go back'
    );
    if (action) {
      const confirmed = window.confirm('Are you sure you want to cancel booking VBE882910? A refund of ₹1,575.00 will be initiated within 5-7 business days.');
      if (confirmed) {
        alert('✅ Cancellation request submitted. Refund of ₹1,575.00 will be credited in 5-7 business days.');
        router.push('/');
      }
    }
  }

  return (
    <main className="pt-28 pb-16 px-4 md:px-8 max-w-6xl mx-auto">
{/* Hero Section / Ticket Header */}
<section className="mb-12 relative overflow-hidden rounded-xl h-48 md:h-64 flex items-end p-8">
<div className="absolute inset-0 z-0">
<img alt="Vande Bharat train" className="w-full h-full object-cover" src="https://lh3.googleusercontent.com/aida-public/AB6AXuDXhD-RFuF3gSuG_NckoAEbHgMirP_kvgfZk8__utbMEwevI6uOwAFIRISsDIRnV6bq97qRVGNJn4jFn6kJ9YHScbUjGOOB_qXcN9DSUuhZHHZC06OwK0goLvIeco6t52KQPaly0hMPrKXvyhB1sLtal8EsOkrAV2WA8iovUX_CA22a8wSYbMK-6LaesBxk3L_bF0Subxjx0U3Wdd0hYeggBg4H6LsdQr4MZYeEYQDACwqqtpattgBJP_1DE2cKk6P6vDjGsV752zEP"/>
<div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent"></div>
</div>
<div className="relative z-10 w-full flex flex-col md:flex-row justify-between items-end gap-4">
<div>
<h1 className="text-white text-4xl md:text-5xl font-black tracking-tighter uppercase mb-2">Digital Ticket</h1>
<p className="text-white/80 font-medium tracking-wide">Booking Reference: VBE882910</p>
</div>
<div className="bg-tertiary-container text-on-tertiary-container px-6 py-2 rounded-full font-bold flex items-center gap-2 shadow-lg">
<span className="material-symbols-outlined text-sm" style={{"fontVariationSettings":"'FILL' 1"}}>check_circle</span>
                    CONFIRMED
                </div>
</div>
</section>
{/* Main Ticket Body */}
<div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
{/* Left Column: Travel Details */}
<div className="lg:col-span-8 space-y-6">
<div className="bg-surface-container-lowest rounded-xl p-8 shadow-sm">
<div className="flex justify-between items-start mb-12">
<div className="space-y-1">
<span className="text-primary font-bold tracking-widest text-xs uppercase">Departure</span>
<h2 className="text-3xl font-black text-on-surface">New Delhi</h2>
<p className="text-on-surface-variant font-medium">NDLS • Platform 16</p>
<p className="text-2xl font-bold mt-2">06:00 AM</p>
</div>
<div className="flex flex-col items-center flex-1 px-4 pt-10">
<div className="w-full h-[2px] bg-outline-variant relative flex items-center justify-center">
<span className="material-symbols-outlined text-primary bg-surface-container-lowest px-2">train</span>
</div>
<span className="text-xs font-bold text-outline mt-2 uppercase tracking-tighter">8h 00m Duration</span>
</div>
<div className="text-right space-y-1">
<span className="text-primary font-bold tracking-widest text-xs uppercase">Arrival</span>
<h2 className="text-3xl font-black text-on-surface">Varanasi</h2>
<p className="text-on-surface-variant font-medium">BSB • Platform 1</p>
<p className="text-2xl font-bold mt-2">02:00 PM</p>
</div>
</div>
{/* Passenger & Seat Info */}
<div className="grid grid-cols-2 md:grid-cols-4 gap-8 py-8 border-t border-surface-container-high">
<div className="flex flex-col">
<span className="text-xs font-bold text-outline uppercase mb-1">Passenger</span>
<span className="font-bold text-on-surface">Rajesh Kumar</span>
</div>
<div className="flex flex-col">
<span className="text-xs font-bold text-outline uppercase mb-1">Coach</span>
<span className="font-bold text-on-surface">C2</span>
</div>
<div className="flex flex-col">
<span className="text-xs font-bold text-outline uppercase mb-1">Seat</span>
<span className="font-bold text-on-surface">24 (Window)</span>
</div>
<div className="flex flex-col">
<span className="text-xs font-bold text-outline uppercase mb-1">Class</span>
<span className="font-bold text-on-surface">AC Chair Car</span>
</div>
</div>
<div className="grid grid-cols-2 md:grid-cols-4 gap-8 py-8 border-t border-surface-container-high">
<div className="flex flex-col">
<span className="text-xs font-bold text-outline uppercase mb-1">Train No</span>
<span className="font-bold text-on-surface">22436</span>
</div>
<div className="flex flex-col">
<span className="text-xs font-bold text-outline uppercase mb-1">Date</span>
<span className="font-bold text-on-surface">Oct 24, 2024</span>
</div>
<div className="flex flex-col">
<span className="text-xs font-bold text-outline uppercase mb-1">PNR</span>
<span className="font-bold text-on-surface">244-9812233</span>
</div>
<div className="flex flex-col">
<span className="text-xs font-bold text-outline uppercase mb-1">Fare</span>
<span className="font-bold text-on-surface">₹ 1,750.00</span>
</div>
</div>
</div>
{/* Action Buttons */}
<div className="flex flex-wrap gap-4">
<button
  onClick={handleDownload}
  disabled={downloading}
  className="kinetic-gradient text-on-primary font-bold px-8 py-4 rounded-lg flex items-center gap-3 shadow-lg shadow-orange-900/10 active:scale-95 transition-all cursor-pointer disabled:opacity-70"
>
<span className="material-symbols-outlined">{downloading ? 'hourglass_empty' : 'download'}</span>
                        {downloading ? 'Preparing...' : 'Download PDF'}
                    </button>
<button
  onClick={handleManageBooking}
  className="bg-secondary-container text-on-secondary-container font-bold px-8 py-4 rounded-lg flex items-center gap-3 active:scale-95 transition-all cursor-pointer hover:opacity-90"
>
<span className="material-symbols-outlined">edit</span>
                        Manage Booking
                    </button>
<button
  onClick={handleShare}
  className={`font-bold px-8 py-4 rounded-lg flex items-center gap-3 active:scale-95 transition-all cursor-pointer ${shared ? 'bg-tertiary-container text-on-tertiary-container' : 'bg-surface-container-high text-on-surface hover:bg-surface-container-highest'}`}
>
<span className="material-symbols-outlined">{shared ? 'check' : 'share'}</span>
                        {shared ? 'Copied!' : 'Share Ticket'}
                    </button>
</div>
</div>
{/* Right Column: QR & Quick Info */}
<div className="lg:col-span-4 space-y-6">
{/* Boarding QR */}
<div className="bg-surface-container-lowest rounded-xl p-8 shadow-sm flex flex-col items-center">
<h3 className="font-bold text-on-surface-variant uppercase tracking-widest text-xs mb-6">Boarding QR Code</h3>
<div className="p-4 bg-white rounded-lg border border-surface-container-high mb-6">
<img alt="QR Code" className="w-48 h-48" src="https://lh3.googleusercontent.com/aida-public/AB6AXuCTvtxJ27OLCbWT-jXKxHiuq6N6bw8AzFzkVsq9-SzWiZpKSYfIZZFAUmAF8C4CY7XvMeK4cxOKVhKMRzD_gQK6I5kBXtrc62Mqbi8EIljkv7zD4r0z7M-Wor5wAqPAu8Zd8rd8CirulDuGm-DuMj315OAqNoFbxsuxBJOy0qjfMnUDyPSUgBG1x5TotXKUgaGnVYNW8FChug4N9YL9Q0IpycpW12JFiA99qvsE2DpkqVTj9B-QQBXjYhPGpJG-TmuSf7ip45mJONcU"/>
</div>
<p className="text-center text-sm text-on-surface-variant px-4">Present this QR code at the boarding gate and to the ticket inspector.</p>
</div>
{/* Velocity Tracker (Custom Component) */}
<div className="bg-surface-container-lowest rounded-xl p-6 shadow-sm">
<h3 className="font-bold text-on-surface-variant uppercase tracking-widest text-xs mb-4">Live Journey Status</h3>
<div className="space-y-4">
<div className="flex justify-between text-xs font-bold text-outline">
<span>NDLS</span>
<span className="text-primary font-black">ON TRACK</span>
<span>BSB</span>
</div>
<div className="relative h-2 bg-surface-container-high rounded-full overflow-hidden">
<div className="absolute left-0 top-0 h-full w-1/3 kinetic-gradient rounded-full shadow-[0_0_12px_rgba(255,153,51,0.6)]"></div>
</div>
<p className="text-xs text-on-surface-variant">Scheduled to depart on time from New Delhi Railway Station.</p>
</div>
</div>
{/* Back to Home */}
<Link
  href="/"
  className="w-full py-4 rounded-xl border-2 border-outline-variant text-on-surface font-bold flex items-center justify-center gap-2 hover:border-primary hover:text-primary transition-all"
>
<span className="material-symbols-outlined">home</span>
  Back to Home
</Link>
</div>
</div>
</main>
  );
}